### PR TITLE
Support `any` type for custom scalars

### PR DESCRIPTION
**Pull request by nikhilmat**
Hi there!

Thanks for writing a great library! This has been immensely useful for us.

In our GraphQL backend, we have a custom scalar used for representing JSON. Currently, this always get represented as a `string` type when the Typescript types are generated. For our custom scalar case, we want this to be an `any` type, so that it can be used like object in our Typescript code.

This PR adds a CLI option to specify the type for custom scalars as any - I didn't see a way for this to be configured on a per scalar basis, but open to any feedback if there's a better way to implement this!

### CODE REVIEW

**Comment by nikhilmat** [comment]
@cartogram is this a PR you would accept? Wondering if there's another way folks are handling custom scalars that are not strings.

**Comment by nikhilmat** [comment]
@lemonmade is this a PR you would accept? Wondering if there's another way folks are handling custom scalars that are not strings.

**Comment by lemonmade** [comment]
Glad it’s been helpful! I am definitely open to something along these lines. They way I was thinking about this is that you would specify a custom type on a per-scalar basis, so you could customize to your heart’s content. That would be a bit more involved as you’d need to basically pass JSON to do it in the CLI. Thoughts?

Out of curiosity, what are you using as a GraphQL client that deserializes the data such that a JSON scalar come stay out as a real object? As far as I know, Apollo does not have a native way of doing this.

**Comment by lemonmade** [comment]
@nikhilmat I just added a change to allow passing custom GraphQL types for custom scalars, look for it in the next version!

**Comment by nikhilmat** [comment]
@lemonmade amazing! i just got started using it today, works great :)

**Pull request closed without merging**
