### PR TITLE
[graphql-mini-transforms] Support importing documents without operations (only fragments)

### LINKED ISSUE #92: [graphql-mini-transforms] Unable to import fragment file in javascript
Hi guys! I'm looking into `graphql-mini-transforms` as possible replacement for `graph-tag/loader`, but ran into one annoying issue. We have some instances where we use apollo's [writeFragment/readFragment](https://www.apollographql.com/docs/react/caching/cache-interaction/#writequery-and-writefragment) to do optimistic store updates. In order to do this we import a `gql` file only containing a fragment definition from a javascript file, and pass that along to `writeFragment({ fragment })`/`readFragment({ fragment })`.

Trying this with `graphql-mini-transforms` unfortunately throws the following error:
```js
ERROR in ./src/.../OptimisticCommentFragment.gql
Module build failed (from ./node_modules/graphql-mini-transforms/webpack.js):
GraphQLError: Syntax Error: Unexpected <EOF>
    at syntaxError (/Users/.../node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/Users/.../node_modules/graphql/language/parser.js:1463:41)
    at Parser.parseDefinition (/Users/.../node_modules/graphql/language/parser.js:157:16)
    at Parser.many (/Users/.../node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/Users/.../node_modules/graphql/language/parser.js:111:25)
    at Object.parse (/Users/.../node_modules/graphql/language/parser.js:36:17)
    at Object.cleanDocument (/Users/.../node_modules/graphql-mini-transforms/lib/document.js:15:42)
    at Object.<anonymous> (/Users/.../node_modules/graphql-mini-transforms/lib/webpack.js:23:68)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/.../node_modules/graphql-mini-transforms/lib/webpack.js:4:58)
```
Any idea what's causing this? Or do fragments currently only work inside of other `gql` files, with the `#import` syntax?

### PR DESCRIPTION
**Pull request by ajhyndman**
Fixes #92 

This approach tries to support documents without operations, as long as it's not ambiguous which fragment should be treated as the default export.

e.g.

This is supported (and not order dependent):

```graphql
fragment FooFragment on Query {
  shop {
    ...BarFragment
  }
}

fragment BarFragment on Shop {
  __typename
}
```

This is not supported:

```graphql
fragment FooFragment on Shop {
  __typename
}

fragment BarFragment on Shop {
  __typename
}
```

I also added a slightly more useful error for debugging unsupported documents.

### CODE REVIEW

**Comment by bennypowers** [comment]
While we wait for maintainers to merge, I've published a fork of this repo with this PR merged at [`@apollo-elements/graphql-mini-transforms`](https://npm.im/@apollo-elements/graphql-mini-transforms). It's being used with [`@apollo-elements/rollup-plugin-graphql`](https://npm.im/@apollo-elements/rollup-plugin-graphql).

My fork also adds an `addTypename` option to `cleanDocument` (default true), as the presence of `__typename` in my documents was causing errors with apollo client 3. I'll issue a PR with that fix shortly

**Comment by ajhyndman** [comment]
@bennypowers Thanks for sharing that here!

**Comment by dahukish** [comment]
@ajhyndman we are currently looking into getting this PR sorry for the radio silence :)

**Comment by michenly** [comment]
👋 So sorry for the trouble, we have move this package to https://github.com/Shopify/quilt/tree/main/packages/graphql-mini-transforms please move this PR over to quilt if you would still like to contribute 🙇‍♀️

**Comment by bennypowers** [comment]
I combined this with #127 in https://github.com/Shopify/quilt/pull/1784

**Pull request closed without merging**
